spotify/reactochart

examples/src/Examples.jsx, package.json, src/AreaChart.js, src/AreaHeatmap.js, src/ColorHeatmap.js, src/FunnelChart.js, src/Histogram.js, src/KernelDensityEstimation.js, src/LineChart.js, src/MarkerLineChart.js, src/PieChart.js, src/TreeMap.js, src/XYPlot.js, src/old/BarChart.js, src/old/XYPlot.js, src/utils/Data.js, src/utils/Margin.js, src/utils/Scale.js, src/utils/resolveXYScales.js
Upgrades d3 to version 4.4.0 and performs the necessary syntax changes.
Todo:
=> d3 version upgrade (4.4.0)

examples/src/Examples.jsx, examples/src/data/util.js, src/AreaChart.js, src/utils/Data.js
Due to the way d3 works, the `AreaChart` component requires a single combined dataset - but sometimes you have two separate datasets which need a shaded area between them. This adds a utility function called `combineDatasets`, which users can use to combine their multiple datasets into a single one with multiple keys, before passing it into the `AreaChart`.
Also adds props called `shouldShowGaps` and `isDefined` which allow users to decide whether or not to represent undefined data as gaps in the area chart (`shouldShowGaps`), and if so, how the chart should determine whether a given datum is defined or undefined (`isDefined` function, which runs on each datum).
Also adds an example showing how to use these features.
=> Updates to AreaChart, new util function for combining datasets

src/SankeyDiagram.js, tests/jsdom/spec/SankeyDiagram.spec.js
Starting in v0.4.2 we allowed the `SankeyDiagram` `nodeLabelText` prop to return an arbitrary HTML element (as opposed to a string) in order to support custom labels which are more complicated than a single text string. These were rendered inside a `<foreignObject>` tag which was positioned using a `translate` transform which attempted to follow all node placement rules and allow the user to use HTML instead of SVG text.
However, @krissalvador27 noticed that positioning of these labels was broken in Chrome when the `SankeyDiagram` is inside of a `ZoomContainer`. Further investigation revealed that Chrome's support for `<foreignObject>` is rather poor, likely due to issues Webkit (see eg. Webkit issues [71819](https://bugs.webkit.org/show_bug.cgi?id=71819) and …
=> Fix for non-string SankeyDiagram nodeLabelText prop

src/utils/resolveXYScales.js
- Fix regression on recursion logic not using correct defaultProps via `static defaultProps = ComposedComponent.defaultProps;`
- Comment out console.warn to prevent multiple warn logs during recursion. It's misleading since domain gets figured out later towards the tail end of the recursion.
=> Fix regression on recursion logic not using correct defaultProps

tests/jsdom/spec/AreaBarChart.spec.js
I added a prop test, since AreaBarChart is a wrapper for `RectRange` components, and the render tests are there. I based this off of the `RangeBarChart` spec example.
=> add AreaBarChart spec

src/XAxis.js, src/XAxisLabels.js, src/YAxis.js, src/YAxisLabels.js, src/utils/Axis.js, tests/browser/spec/XAxisLabels.spec.js, tests/browser/spec/YAxisLabels.spec.js, tests/jsdom/spec/utils.Axis.spec.js
This adds offset to the x and y labels. This sets up use cases like so
=> Add offset prop to x and y labels

docs/build/index.html, docs/src/docs/XAxis/propDocs.json, docs/src/docs/YAxis/propDocs.json, src/XAxis.js, src/YAxis.js, styles/charts.less, tests/browser/spec/XAxis.spec.js, tests/browser/spec/YAxis.spec.js
Realized the X/Y axis line never had default styles so the line wouldn't appear without adding `.rct-chart-axis-line-x` to your stylesheet and adding a stroke color. Also added a prop called `showLine` for whether or not users want to show the actual X/Y axis line, accompanied with their own `lineStyle` object
=> Add show line prop and default style for X and Y Axis

docs/build/index.html, docs/src/docs/Bar/propDocs.json, docs/src/docs/RangeBarChart/propDocs.json, src/Bar.js, src/RangeBarChart.js, tests/jsdom/spec/Bar.spec.js
Allow users to optionally show the values of the bar in the bar chart.
- Includes text class for changing the styles
- Works for both horizontal and vertical bars, but only displays to the right of horizontal bars
- Includes formatting function prop for changing how the values display
=> Add display value of bar chart

src/XYPlot.js
Fix a regression with the property translation to variable being omitted
=> [bug] fix xyPlotClassName omission

docs/build/index.html, docs/src/docs/XYPlot/examples/XYPlot.js.example, src/XYPlot.js, tests/jsdom/spec/XYPlot.spec.js
Some XYPlot props conflict with RangeRect and Bar component's props. Omitting those props from being sent downstream.
Also added new xyPlotStyle prop which is added to the area where the graphs are plotted (within the axes but not including the axes).
=> Namespace XYPlot style prop from overriding children styles

docs/src/ExampleSection.js, package-lock.json, package.json, tests/browser/spec/XAxisLabels.spec.js, tests/jsdom/setup.js, tests/jsdom/spec/FunnelChart.spec.js, tests/jsdom/spec/LineChart.spec.js, tests/jsdom/spec/TreeMap.spec.js, tests/jsdom/spec/XGrid.spec.js, tests/jsdom/spec/XYPlot.spec.js, tests/jsdom/spec/YGrid.spec.js, tests/jsdom/spec/ZoomContainer.spec.js
- upgrade packages to react v16 and fix necessary dependencies (react-dom, react-test-renderer, enzyme, chai)
- reconfigure peer dependencies
- update tests after enzyme v3 upgrade
=> Upgrade react

docs/src/docs/PieChart/examples/PieChart.js.example, src/PieChart.js, tests/jsdom/spec/PieChart.spec.js
Adds 3 new props to render and style labels associated with each slice of the pie chart. I chose names that I felt matched the terminology in the pie chart component, but open to using other (possibly shorter) prop names. 
Adds a couple tests to verify the new behavior, but I wasn't sure of a good way to test the distance calculations without testing the implementation details. Any thoughts?
=> Add support for pie chart slice labels

package-lock.json, src/XAxisLabels.js, src/YAxisLabels.js
If users pass in labelStyle function, it's expected to be called with an object, not just the value of the label
=> Fix labelStyle argument

src/utils/Scale.js, tests/jsdom/spec/utils.Axis.spec.js, tests/jsdom/spec/utils.Scale.spec.js
Bug fix to get the correct option/datum/category that the user's mouse is hovering over when the chart is using ordinal/point scale
=> Fix invert point scale logic to get option closest to mouse pointer

docs/src/docs/XLine/propDocs.json, docs/src/docs/YLine/propDocs.json, src/XLine.js, src/YLine.js, tests/jsdom/spec/XLine.spec.js, tests/jsdom/spec/YLine.spec.js
Adds the height/width limit props discussed in #149
=> Add limit props to set height and width of XLine and YLine respectively

docs/src/ExampleSection.js, package-lock.json, package.json, src/XAxisLabels.js, src/YAxisLabels.js, src/utils/Label.js, tests/browser/spec/XAxisLabels.spec.js, tests/browser/spec/YAxisLabels.spec.js
Deprecates moment in favor of d3 time format. This is a breaking change because the `formats` array passed into `XAxisLabels` and `YAxisLabels` accepted moment's format strings when handling date types, as opposed to d3 time format which uses [strptime and strftime](https://github.com/d3/d3-time-format#locale_format). 
These changes will be merged into the `2.0.0-rc.0` branch.
Addresses issue #158
=> Deprecate moment in favor of d3 time format

docs/src/docs/XYPlot/examples/XYPlot.js.example, src/Bar.js, src/XYPlot.js, tests/jsdom/spec/XYPlot.spec.js
This will be for v2 release
- Update prop omission logic in XYPlot
- rename `style` prop to `xyPlotContainerStyle` for better descriptiveness
=> Namespace xy plot props

src/YAxisTitle.js
Fixes proptype warning for YAxisTitle if passing in something other than a string
=> Fix children proptype for YAxisTitle

src/XYPlot.js
- Created a binding declaration for the onMouseEnter and onMouseLeave events similar to the onClick, onMouseDown etc. events for XYPlot
- Removed original declaration of onMouseEnter and onMouseLeave events
- Closes #176
=> Decorate XYPlot onMouseEnter and onMouseLeave events

.eslintrc.json, package-lock.json, package.json, src/SankeyDiagram.js, tests/jsdom/spec/AreaBarChart.spec.js, tests/jsdom/spec/Bar.spec.js, tests/jsdom/spec/SankeyDiagram.spec.js, tests/jsdom/spec/XLine.spec.js, tests/jsdom/spec/XYPlot.spec.js
- Add tests for mouse events in `XYPlot.spec.js`
- Fix warnings in `Bar.spec.js`
- Fix warnings in `XLine.spec.js`
- Fix warnings in `AreaBarChart.spec.js`
- Add test for SankeyNodeTerminal in `SankeyDiagram.spec.js`
- Eslint fixes on `SankeyDiagram.spec.js`
- Allow chai assertions for eslint
Also added an issue #183 to update our test suite to use jest instead of mocha, chai and sinon.
=> Fix warnings in tests and add SankeyNodeTerminal tests

docs/src/App.js, docs/src/lessons/GettersAndAccessors/GettersAndAccessorsLesson.js, docs/src/lessons/XYPlots/XYPlotsLesson.js
Reported by @scottsheffield, the XYPlot lesson in the docs is showing a blank page. The bug and corresponding fix is related to the raw-loader upgrade here https://github.com/spotify/reactochart/pull/195/commits/c817b5be821564334cb777771a381a6d37464b17
=> Fix xy plot lesson in docs

docs/src/docs/PieChart/examples/PieChart.js.example, docs/src/docs/TreeMap/examples/AnimatedTreeMap.js.example, src/KernelDensityEstimation.js, src/LineChart.js, src/SankeyDiagram.js, src/TreeMap.js, src/ZoomContainer.js
`componentWillReceiveProps` => `UNSAFE_componentWillReceiveProps`
`componentWillUpdate` => `UNSAFE_componentWillUpdate`
Apparently in React 17.x these will continue to work 🎉 but also they're still unsafe 😒 
addresses #181
=> Rename upcoming deprecated Lifecycle methods

docs/src/docs/PieChart/examples/PieChart.js.example, docs/src/docs/TreeMap/examples/AnimatedTreeMap.js.example, src/KernelDensityEstimation.js, src/LineChart.js, src/SankeyDiagram.js, src/TreeMap.js, src/ZoomContainer.js, tests/jsdom/spec/TreeMap.spec.js
Fixes #181 
Remove calls prefixed with "UNSAFE_".
I've tested locally with internal apps that cover LineChart, SankeyDiagram, ZoomContainer (with controls). I haven't tested TreeMap or KernelDensityEstimation, so if there's somebody working on app that uses those, it would be great if they could give it a quick test. This shouldn't be required though.
Each commit can be reviewed individually.
=> Remove deprecated Lifecycle hooks

docs/src/docs/BarChart/BarChartDocs.js, docs/src/docs/BarChart/examples/BarChartLinearGradient.js.example
I found a way to accomplish this without any code changes, so I've closed #248 and just updated the docs with this example:
=> bar chart gradient example in docs

src/SankeyDiagram.js, src/ZoomContainer.js
* Remove deprecate refs definition using strings. For some reason this was breaking local development using `npm link` and it's good to fix.
* Add `nodeSort` and `linkSort` hooks to SankeyDiagram component.
=> Sankey sorting

docs/src/docs/YAxisLabels/examples/YAxisLabels.js.example
The current example did not demonstrate label color/weight change, since the final label (`label.text`) never was `20.00`.
=> Small YAxisLabels formatting example fix

src/AreaChart.js, src/AreaHeatmap.js, src/Bar.js, src/ColorHeatmap.js, src/FunnelChart.js, src/LineChart.js, src/MarkerLineChart.js, src/RangeBarChart.js, src/RangeRect.js, src/ScatterPlot.js, src/XAxis.js, src/XAxisLabels.js, src/XAxisTitle.js, src/XGrid.js, src/XLine.js, src/XTicks.js, src/XYPlot.js, src/YAxis.js, src/YAxisLabels.js, src/YAxisTitle.js, src/YGrid.js, src/YLine.js, src/YTicks.js
I was able to add `aria-hidden="true"` attributes to `XYPlot` components which essentially skip these charts when navigating with screen readers.
This does not provide accessibility to visualizations that don't use `XYPlot`, but does hide everything within an `XYPlot`
=> [A11y] add aria-hidden attributes to XYPlot
